use crate::abi::{TIFFDataType, TIFFField, TIFFFieldArray, TIFFFieldArrayType, TIFFSetGetFieldType};
use libc::c_char;

macro_rules! array_ptr {
    ($name:ident) => {
        std::ptr::addr_of!($name) as *mut TIFFFieldArray
    };
}

macro_rules! field {
    ($tag:expr, $read:expr, $write:expr, $ty:ident, $anonymous:expr, $set:ident, $get:ident, $bit:expr, $ok:expr, $pass:expr, $name:literal, $subfields:expr) => {
        TIFFField {
            field_tag: $tag,
            field_readcount: $read,
            field_writecount: $write,
            field_type: TIFFDataType::$ty,
            field_anonymous: $anonymous,
            set_field_type: TIFFSetGetFieldType::$set,
            get_field_type: TIFFSetGetFieldType::$get,
            field_bit: $bit,
            field_oktochange: $ok,
            field_passcount: $pass,
            field_name: concat!($name, "\0").as_ptr() as *mut c_char,
            field_subfields: $subfields,
        }
    };
}

pub(crate) static TIFF_FIELDS_IMAGE: [TIFFField; 160] = [
    field!(254, 1, 1, TIFF_LONG, 0, TIFF_SETGET_UINT32, TIFF_SETGET_UNDEFINED, 5, 1, 0, "SubfileType", std::ptr::null_mut()),
    field!(255, 1, 1, TIFF_SHORT, 0, TIFF_SETGET_UNDEFINED, TIFF_SETGET_UNDEFINED, 0, 1, 0, "OldSubfileType", std::ptr::null_mut()),
    field!(256, 1, 1, TIFF_LONG, 0, TIFF_SETGET_UINT32, TIFF_SETGET_UNDEFINED, 1, 0, 0, "ImageWidth", std::ptr::null_mut()),
    field!(257, 1, 1, TIFF_LONG, 0, TIFF_SETGET_UINT32, TIFF_SETGET_UNDEFINED, 1, 1, 0, "ImageLength", std::ptr::null_mut()),
    field!(258, 1, 1, TIFF_SHORT, 0, TIFF_SETGET_UINT16, TIFF_SETGET_UNDEFINED, 6, 0, 0, "BitsPerSample", std::ptr::null_mut()),
    field!(259, 1, 1, TIFF_SHORT, 0, TIFF_SETGET_UINT16, TIFF_SETGET_UNDEFINED, 7, 0, 0, "Compression", std::ptr::null_mut()),
    field!(262, 1, 1, TIFF_SHORT, 0, TIFF_SETGET_UINT16, TIFF_SETGET_UNDEFINED, 8, 0, 0, "PhotometricInterpretation", std::ptr::null_mut()),
    field!(263, 1, 1, TIFF_SHORT, 0, TIFF_SETGET_UINT16, TIFF_SETGET_UNDEFINED, 9, 1, 0, "Threshholding", std::ptr::null_mut()),
    field!(264, 1, 1, TIFF_SHORT, 0, TIFF_SETGET_UINT16, TIFF_SETGET_UNDEFINED, 65, 1, 0, "CellWidth", std::ptr::null_mut()),
    field!(265, 1, 1, TIFF_SHORT, 0, TIFF_SETGET_UINT16, TIFF_SETGET_UNDEFINED, 65, 1, 0, "CellLength", std::ptr::null_mut()),
    field!(266, 1, 1, TIFF_SHORT, 0, TIFF_SETGET_UINT16, TIFF_SETGET_UNDEFINED, 10, 0, 0, "FillOrder", std::ptr::null_mut()),
    field!(292, 1, 1, TIFF_LONG, 0, TIFF_SETGET_UINT32, TIFF_SETGET_UINT32, 66, 0, 0, "Group3Options", std::ptr::null_mut()),
    field!(293, 1, 1, TIFF_LONG, 0, TIFF_SETGET_UINT32, TIFF_SETGET_UINT32, 67, 0, 0, "Group4Options", std::ptr::null_mut()),
    field!(269, -1, -1, TIFF_ASCII, 0, TIFF_SETGET_ASCII, TIFF_SETGET_UNDEFINED, 65, 1, 0, "DocumentName", std::ptr::null_mut()),
    field!(270, -1, -1, TIFF_ASCII, 0, TIFF_SETGET_ASCII, TIFF_SETGET_UNDEFINED, 65, 1, 0, "ImageDescription", std::ptr::null_mut()),
    field!(271, -1, -1, TIFF_ASCII, 0, TIFF_SETGET_ASCII, TIFF_SETGET_UNDEFINED, 65, 1, 0, "Make", std::ptr::null_mut()),
    field!(272, -1, -1, TIFF_ASCII, 0, TIFF_SETGET_ASCII, TIFF_SETGET_UNDEFINED, 65, 1, 0, "Model", std::ptr::null_mut()),
    field!(273, -1, -1, TIFF_LONG8, 0, TIFF_SETGET_UNDEFINED, TIFF_SETGET_UNDEFINED, 25, 0, 0, "StripOffsets", std::ptr::null_mut()),
    field!(274, 1, 1, TIFF_SHORT, 0, TIFF_SETGET_UINT16, TIFF_SETGET_UNDEFINED, 15, 0, 0, "Orientation", std::ptr::null_mut()),
    field!(277, 1, 1, TIFF_SHORT, 0, TIFF_SETGET_UINT16, TIFF_SETGET_UNDEFINED, 16, 0, 0, "SamplesPerPixel", std::ptr::null_mut()),
    field!(278, 1, 1, TIFF_LONG, 0, TIFF_SETGET_UINT32, TIFF_SETGET_UNDEFINED, 17, 0, 0, "RowsPerStrip", std::ptr::null_mut()),
    field!(279, -1, -1, TIFF_LONG8, 0, TIFF_SETGET_UNDEFINED, TIFF_SETGET_UNDEFINED, 24, 0, 0, "StripByteCounts", std::ptr::null_mut()),
    field!(280, -2, -1, TIFF_SHORT, 0, TIFF_SETGET_UINT16, TIFF_SETGET_UNDEFINED, 18, 1, 0, "MinSampleValue", std::ptr::null_mut()),
    field!(281, -2, -1, TIFF_SHORT, 0, TIFF_SETGET_UINT16, TIFF_SETGET_UNDEFINED, 19, 1, 0, "MaxSampleValue", std::ptr::null_mut()),
    field!(282, 1, 1, TIFF_RATIONAL, 0, TIFF_SETGET_FLOAT, TIFF_SETGET_UNDEFINED, 3, 1, 0, "XResolution", std::ptr::null_mut()),
    field!(283, 1, 1, TIFF_RATIONAL, 0, TIFF_SETGET_FLOAT, TIFF_SETGET_UNDEFINED, 3, 1, 0, "YResolution", std::ptr::null_mut()),
    field!(284, 1, 1, TIFF_SHORT, 0, TIFF_SETGET_UINT16, TIFF_SETGET_UNDEFINED, 20, 0, 0, "PlanarConfiguration", std::ptr::null_mut()),
    field!(285, -1, -1, TIFF_ASCII, 0, TIFF_SETGET_ASCII, TIFF_SETGET_UNDEFINED, 65, 1, 0, "PageName", std::ptr::null_mut()),
    field!(286, 1, 1, TIFF_RATIONAL, 0, TIFF_SETGET_FLOAT, TIFF_SETGET_UNDEFINED, 4, 1, 0, "XPosition", std::ptr::null_mut()),
    field!(287, 1, 1, TIFF_RATIONAL, 0, TIFF_SETGET_FLOAT, TIFF_SETGET_UNDEFINED, 4, 1, 0, "YPosition", std::ptr::null_mut()),
    field!(288, -1, -1, TIFF_LONG8, 0, TIFF_SETGET_UNDEFINED, TIFF_SETGET_UNDEFINED, 0, 0, 0, "FreeOffsets", std::ptr::null_mut()),
    field!(289, -1, -1, TIFF_LONG8, 0, TIFF_SETGET_UNDEFINED, TIFF_SETGET_UNDEFINED, 0, 0, 0, "FreeByteCounts", std::ptr::null_mut()),
    field!(290, 1, 1, TIFF_SHORT, 0, TIFF_SETGET_UNDEFINED, TIFF_SETGET_UNDEFINED, 0, 1, 0, "GrayResponseUnit", std::ptr::null_mut()),
    field!(291, -1, -1, TIFF_SHORT, 0, TIFF_SETGET_UNDEFINED, TIFF_SETGET_UNDEFINED, 0, 1, 0, "GrayResponseCurve", std::ptr::null_mut()),
    field!(296, 1, 1, TIFF_SHORT, 0, TIFF_SETGET_UINT16, TIFF_SETGET_UNDEFINED, 22, 1, 0, "ResolutionUnit", std::ptr::null_mut()),
    field!(297, 2, 2, TIFF_SHORT, 0, TIFF_SETGET_UINT16_PAIR, TIFF_SETGET_UNDEFINED, 23, 1, 0, "PageNumber", std::ptr::null_mut()),
    field!(300, 1, 1, TIFF_SHORT, 0, TIFF_SETGET_UNDEFINED, TIFF_SETGET_UNDEFINED, 0, 1, 0, "ColorResponseUnit", std::ptr::null_mut()),
    field!(301, -1, -1, TIFF_SHORT, 0, TIFF_SETGET_OTHER, TIFF_SETGET_UNDEFINED, 44, 1, 0, "TransferFunction", std::ptr::null_mut()),
    field!(305, -1, -1, TIFF_ASCII, 0, TIFF_SETGET_ASCII, TIFF_SETGET_UNDEFINED, 65, 1, 0, "Software", std::ptr::null_mut()),
    field!(306, 20, 20, TIFF_ASCII, 0, TIFF_SETGET_ASCII, TIFF_SETGET_UNDEFINED, 65, 1, 0, "DateTime", std::ptr::null_mut()),
    field!(315, -1, -1, TIFF_ASCII, 0, TIFF_SETGET_ASCII, TIFF_SETGET_UNDEFINED, 65, 1, 0, "Artist", std::ptr::null_mut()),
    field!(316, -1, -1, TIFF_ASCII, 0, TIFF_SETGET_ASCII, TIFF_SETGET_UNDEFINED, 65, 1, 0, "HostComputer", std::ptr::null_mut()),
    field!(317, 1, 1, TIFF_SHORT, 0, TIFF_SETGET_UINT16, TIFF_SETGET_UNDEFINED, 68, 1, 0, "Predictor", std::ptr::null_mut()),
    field!(318, 2, 2, TIFF_RATIONAL, 0, TIFF_SETGET_C0_FLOAT, TIFF_SETGET_UNDEFINED, 65, 1, 0, "WhitePoint", std::ptr::null_mut()),
    field!(319, 6, 6, TIFF_RATIONAL, 0, TIFF_SETGET_C0_FLOAT, TIFF_SETGET_UNDEFINED, 65, 1, 0, "PrimaryChromaticities", std::ptr::null_mut()),
    field!(320, -1, -1, TIFF_SHORT, 0, TIFF_SETGET_OTHER, TIFF_SETGET_UNDEFINED, 26, 1, 0, "ColorMap", std::ptr::null_mut()),
    field!(321, 2, 2, TIFF_SHORT, 0, TIFF_SETGET_UINT16_PAIR, TIFF_SETGET_UNDEFINED, 37, 1, 0, "HalftoneHints", std::ptr::null_mut()),
    field!(322, 1, 1, TIFF_LONG, 0, TIFF_SETGET_UINT32, TIFF_SETGET_UNDEFINED, 2, 0, 0, "TileWidth", std::ptr::null_mut()),
    field!(323, 1, 1, TIFF_LONG, 0, TIFF_SETGET_UINT32, TIFF_SETGET_UNDEFINED, 2, 0, 0, "TileLength", std::ptr::null_mut()),
    field!(324, -1, 1, TIFF_LONG8, 0, TIFF_SETGET_UNDEFINED, TIFF_SETGET_UNDEFINED, 25, 0, 0, "TileOffsets", std::ptr::null_mut()),
    field!(325, -1, 1, TIFF_LONG8, 0, TIFF_SETGET_UNDEFINED, TIFF_SETGET_UNDEFINED, 24, 0, 0, "TileByteCounts", std::ptr::null_mut()),
    field!(326, 1, 1, TIFF_LONG, 0, TIFF_SETGET_UINT32, TIFF_SETGET_UINT32, 72, 1, 0, "BadFaxLines", std::ptr::null_mut()),
    field!(327, 1, 1, TIFF_SHORT, 0, TIFF_SETGET_UINT16, TIFF_SETGET_UINT16, 73, 1, 0, "CleanFaxData", std::ptr::null_mut()),
    field!(328, 1, 1, TIFF_LONG, 0, TIFF_SETGET_UINT32, TIFF_SETGET_UINT32, 74, 1, 0, "ConsecutiveBadFaxLines", std::ptr::null_mut()),
    field!(330, -1, -1, TIFF_IFD8, 0, TIFF_SETGET_C16_IFD8, TIFF_SETGET_UNDEFINED, 49, 1, 1, "SubIFD", array_ptr!(TIFF_FIELD_ARRAY_IMAGE)),
    field!(332, 1, 1, TIFF_SHORT, 0, TIFF_SETGET_UINT16, TIFF_SETGET_UNDEFINED, 65, 0, 0, "InkSet", std::ptr::null_mut()),
    field!(333, -1, -1, TIFF_ASCII, 0, TIFF_SETGET_C16_ASCII, TIFF_SETGET_UNDEFINED, 46, 1, 1, "InkNames", std::ptr::null_mut()),
    field!(334, 1, 1, TIFF_SHORT, 0, TIFF_SETGET_UINT16, TIFF_SETGET_UNDEFINED, 50, 1, 0, "NumberOfInks", std::ptr::null_mut()),
    field!(336, 2, 2, TIFF_SHORT, 0, TIFF_SETGET_UINT16_PAIR, TIFF_SETGET_UNDEFINED, 65, 0, 0, "DotRange", std::ptr::null_mut()),
    field!(337, -1, -1, TIFF_ASCII, 0, TIFF_SETGET_ASCII, TIFF_SETGET_UNDEFINED, 65, 1, 0, "TargetPrinter", std::ptr::null_mut()),
    field!(338, -1, -1, TIFF_SHORT, 0, TIFF_SETGET_C16_UINT16, TIFF_SETGET_UNDEFINED, 31, 0, 1, "ExtraSamples", std::ptr::null_mut()),
    field!(339, -1, -1, TIFF_SHORT, 0, TIFF_SETGET_UINT16, TIFF_SETGET_UNDEFINED, 32, 0, 0, "SampleFormat", std::ptr::null_mut()),
    field!(340, -2, -1, TIFF_NOTYPE, 0, TIFF_SETGET_DOUBLE, TIFF_SETGET_UNDEFINED, 33, 1, 0, "SMinSampleValue", std::ptr::null_mut()),
    field!(341, -2, -1, TIFF_NOTYPE, 0, TIFF_SETGET_DOUBLE, TIFF_SETGET_UNDEFINED, 34, 1, 0, "SMaxSampleValue", std::ptr::null_mut()),
    field!(343, -3, -3, TIFF_BYTE, 0, TIFF_SETGET_C32_UINT8, TIFF_SETGET_UNDEFINED, 65, 0, 1, "ClipPath", std::ptr::null_mut()),
    field!(344, 1, 1, TIFF_LONG, 0, TIFF_SETGET_UINT32, TIFF_SETGET_UNDEFINED, 65, 0, 0, "XClipPathUnits", std::ptr::null_mut()),
    field!(345, 1, 1, TIFF_LONG, 0, TIFF_SETGET_UINT32, TIFF_SETGET_UNDEFINED, 65, 0, 0, "YClipPathUnits", std::ptr::null_mut()),
    field!(529, 3, 3, TIFF_RATIONAL, 0, TIFF_SETGET_C0_FLOAT, TIFF_SETGET_UNDEFINED, 65, 0, 0, "YCbCrCoefficients", std::ptr::null_mut()),
    field!(530, 2, 2, TIFF_SHORT, 0, TIFF_SETGET_UINT16_PAIR, TIFF_SETGET_UNDEFINED, 39, 0, 0, "YCbCrSubsampling", std::ptr::null_mut()),
    field!(531, 1, 1, TIFF_SHORT, 0, TIFF_SETGET_UINT16, TIFF_SETGET_UNDEFINED, 40, 0, 0, "YCbCrPositioning", std::ptr::null_mut()),
    field!(532, 6, 6, TIFF_RATIONAL, 0, TIFF_SETGET_C0_FLOAT, TIFF_SETGET_UNDEFINED, 41, 1, 0, "ReferenceBlackWhite", std::ptr::null_mut()),
    field!(700, -3, -3, TIFF_BYTE, 0, TIFF_SETGET_C32_UINT8, TIFF_SETGET_UNDEFINED, 65, 1, 1, "XMLPacket", std::ptr::null_mut()),
    field!(32995, 1, 1, TIFF_SHORT, 0, TIFF_SETGET_UINT16, TIFF_SETGET_UNDEFINED, 31, 0, 0, "Matteing", std::ptr::null_mut()),
    field!(32996, -2, -1, TIFF_SHORT, 0, TIFF_SETGET_UINT16, TIFF_SETGET_UNDEFINED, 32, 0, 0, "DataType", std::ptr::null_mut()),
    field!(32997, 1, 1, TIFF_LONG, 0, TIFF_SETGET_UINT32, TIFF_SETGET_UNDEFINED, 35, 0, 0, "ImageDepth", std::ptr::null_mut()),
    field!(32998, 1, 1, TIFF_LONG, 0, TIFF_SETGET_UINT32, TIFF_SETGET_UNDEFINED, 36, 0, 0, "TileDepth", std::ptr::null_mut()),
    field!(33300, 1, 1, TIFF_LONG, 0, TIFF_SETGET_UINT32, TIFF_SETGET_UNDEFINED, 65, 1, 0, "ImageFullWidth", std::ptr::null_mut()),
    field!(33301, 1, 1, TIFF_LONG, 0, TIFF_SETGET_UINT32, TIFF_SETGET_UNDEFINED, 65, 1, 0, "ImageFullLength", std::ptr::null_mut()),
    field!(33302, -1, -1, TIFF_ASCII, 0, TIFF_SETGET_ASCII, TIFF_SETGET_UNDEFINED, 65, 1, 0, "TextureFormat", std::ptr::null_mut()),
    field!(33303, -1, -1, TIFF_ASCII, 0, TIFF_SETGET_ASCII, TIFF_SETGET_UNDEFINED, 65, 1, 0, "TextureWrapModes", std::ptr::null_mut()),
    field!(33304, 1, 1, TIFF_FLOAT, 0, TIFF_SETGET_FLOAT, TIFF_SETGET_UNDEFINED, 65, 1, 0, "FieldOfViewCotangent", std::ptr::null_mut()),
    field!(33305, 16, 16, TIFF_FLOAT, 0, TIFF_SETGET_C0_FLOAT, TIFF_SETGET_UNDEFINED, 65, 1, 0, "MatrixWorldToScreen", std::ptr::null_mut()),
    field!(33306, 16, 16, TIFF_FLOAT, 0, TIFF_SETGET_C0_FLOAT, TIFF_SETGET_UNDEFINED, 65, 1, 0, "MatrixWorldToCamera", std::ptr::null_mut()),
    field!(33432, -1, -1, TIFF_ASCII, 0, TIFF_SETGET_ASCII, TIFF_SETGET_UNDEFINED, 65, 1, 0, "Copyright", std::ptr::null_mut()),
    field!(33723, -3, -3, TIFF_UNDEFINED, 0, TIFF_SETGET_C32_UINT8, TIFF_SETGET_UNDEFINED, 65, 1, 1, "RichTIFFIPTC", std::ptr::null_mut()),
    field!(34377, -3, -3, TIFF_BYTE, 0, TIFF_SETGET_C32_UINT8, TIFF_SETGET_UNDEFINED, 65, 1, 1, "Photoshop", std::ptr::null_mut()),
    field!(34665, 1, 1, TIFF_IFD8, 0, TIFF_SETGET_IFD8, TIFF_SETGET_UNDEFINED, 65, 1, 0, "EXIFIFDOffset", array_ptr!(TIFF_FIELD_ARRAY_EXIF)),
    field!(34675, -3, -3, TIFF_UNDEFINED, 0, TIFF_SETGET_C32_UINT8, TIFF_SETGET_UNDEFINED, 65, 1, 1, "ICC Profile", std::ptr::null_mut()),
    field!(34853, 1, 1, TIFF_IFD8, 0, TIFF_SETGET_IFD8, TIFF_SETGET_UNDEFINED, 65, 1, 0, "GPSIFDOffset", array_ptr!(TIFF_FIELD_ARRAY_GPS)),
    field!(34908, 1, 1, TIFF_LONG, 0, TIFF_SETGET_UINT32, TIFF_SETGET_UINT32, 65, 1, 0, "FaxRecvParams", std::ptr::null_mut()),
    field!(34909, -1, -1, TIFF_ASCII, 0, TIFF_SETGET_ASCII, TIFF_SETGET_ASCII, 65, 1, 0, "FaxSubAddress", std::ptr::null_mut()),
    field!(34910, 1, 1, TIFF_LONG, 0, TIFF_SETGET_UINT32, TIFF_SETGET_UINT32, 65, 1, 0, "FaxRecvTime", std::ptr::null_mut()),
    field!(34911, -1, -1, TIFF_ASCII, 0, TIFF_SETGET_ASCII, TIFF_SETGET_ASCII, 65, 1, 0, "FaxDcs", std::ptr::null_mut()),
    field!(37439, 1, 1, TIFF_DOUBLE, 0, TIFF_SETGET_DOUBLE, TIFF_SETGET_UNDEFINED, 65, 0, 0, "StoNits", std::ptr::null_mut()),
    field!(37724, -3, -3, TIFF_UNDEFINED, 0, TIFF_SETGET_C32_UINT8, TIFF_SETGET_UNDEFINED, 65, 1, 1, "Adobe Photoshop Document Data Block", std::ptr::null_mut()),
    field!(40965, 1, 1, TIFF_IFD8, 0, TIFF_SETGET_IFD8, TIFF_SETGET_UNDEFINED, 65, 0, 0, "InteroperabilityIFDOffset", std::ptr::null_mut()),
    field!(50706, 4, 4, TIFF_BYTE, 0, TIFF_SETGET_C0_UINT8, TIFF_SETGET_UNDEFINED, 65, 1, 0, "DNGVersion", std::ptr::null_mut()),
    field!(50707, 4, 4, TIFF_BYTE, 0, TIFF_SETGET_C0_UINT8, TIFF_SETGET_UNDEFINED, 65, 1, 0, "DNGBackwardVersion", std::ptr::null_mut()),
    field!(50708, -1, -1, TIFF_ASCII, 0, TIFF_SETGET_ASCII, TIFF_SETGET_UNDEFINED, 65, 1, 0, "UniqueCameraModel", std::ptr::null_mut()),
    field!(50709, -1, -1, TIFF_BYTE, 0, TIFF_SETGET_C16_UINT8, TIFF_SETGET_UNDEFINED, 65, 1, 1, "LocalizedCameraModel", std::ptr::null_mut()),
    field!(50710, -1, -1, TIFF_BYTE, 0, TIFF_SETGET_C16_UINT8, TIFF_SETGET_UNDEFINED, 65, 1, 1, "CFAPlaneColor", std::ptr::null_mut()),
    field!(50711, 1, 1, TIFF_SHORT, 0, TIFF_SETGET_UINT16, TIFF_SETGET_UNDEFINED, 65, 1, 0, "CFALayout", std::ptr::null_mut()),
    field!(50712, -1, -1, TIFF_SHORT, 0, TIFF_SETGET_C16_UINT16, TIFF_SETGET_UNDEFINED, 65, 1, 1, "LinearizationTable", std::ptr::null_mut()),
    field!(50713, 2, 2, TIFF_SHORT, 0, TIFF_SETGET_C0_UINT16, TIFF_SETGET_UNDEFINED, 65, 1, 0, "BlackLevelRepeatDim", std::ptr::null_mut()),
    field!(50714, -1, -1, TIFF_RATIONAL, 0, TIFF_SETGET_C16_FLOAT, TIFF_SETGET_UNDEFINED, 65, 1, 1, "BlackLevel", std::ptr::null_mut()),
    field!(50715, -1, -1, TIFF_SRATIONAL, 0, TIFF_SETGET_C16_FLOAT, TIFF_SETGET_UNDEFINED, 65, 1, 1, "BlackLevelDeltaH", std::ptr::null_mut()),
    field!(50716, -1, -1, TIFF_SRATIONAL, 0, TIFF_SETGET_C16_FLOAT, TIFF_SETGET_UNDEFINED, 65, 1, 1, "BlackLevelDeltaV", std::ptr::null_mut()),
    field!(50717, -1, -1, TIFF_LONG, 0, TIFF_SETGET_C16_UINT32, TIFF_SETGET_UNDEFINED, 65, 1, 1, "WhiteLevel", std::ptr::null_mut()),
    field!(50718, 2, 2, TIFF_RATIONAL, 0, TIFF_SETGET_C0_FLOAT, TIFF_SETGET_UNDEFINED, 65, 1, 0, "DefaultScale", std::ptr::null_mut()),
    field!(50780, 1, 1, TIFF_RATIONAL, 0, TIFF_SETGET_FLOAT, TIFF_SETGET_UNDEFINED, 65, 1, 0, "BestQualityScale", std::ptr::null_mut()),
    field!(50719, 2, 2, TIFF_RATIONAL, 0, TIFF_SETGET_C0_FLOAT, TIFF_SETGET_UNDEFINED, 65, 1, 0, "DefaultCropOrigin", std::ptr::null_mut()),
    field!(50720, 2, 2, TIFF_RATIONAL, 0, TIFF_SETGET_C0_FLOAT, TIFF_SETGET_UNDEFINED, 65, 1, 0, "DefaultCropSize", std::ptr::null_mut()),
    field!(50721, -1, -1, TIFF_SRATIONAL, 0, TIFF_SETGET_C16_FLOAT, TIFF_SETGET_UNDEFINED, 65, 1, 1, "ColorMatrix1", std::ptr::null_mut()),
    field!(50722, -1, -1, TIFF_SRATIONAL, 0, TIFF_SETGET_C16_FLOAT, TIFF_SETGET_UNDEFINED, 65, 1, 1, "ColorMatrix2", std::ptr::null_mut()),
    field!(50723, -1, -1, TIFF_SRATIONAL, 0, TIFF_SETGET_C16_FLOAT, TIFF_SETGET_UNDEFINED, 65, 1, 1, "CameraCalibration1", std::ptr::null_mut()),
    field!(50724, -1, -1, TIFF_SRATIONAL, 0, TIFF_SETGET_C16_FLOAT, TIFF_SETGET_UNDEFINED, 65, 1, 1, "CameraCalibration2", std::ptr::null_mut()),
    field!(50725, -1, -1, TIFF_SRATIONAL, 0, TIFF_SETGET_C16_FLOAT, TIFF_SETGET_UNDEFINED, 65, 1, 1, "ReductionMatrix1", std::ptr::null_mut()),
    field!(50726, -1, -1, TIFF_SRATIONAL, 0, TIFF_SETGET_C16_FLOAT, TIFF_SETGET_UNDEFINED, 65, 1, 1, "ReductionMatrix2", std::ptr::null_mut()),
    field!(50727, -1, -1, TIFF_RATIONAL, 0, TIFF_SETGET_C16_FLOAT, TIFF_SETGET_UNDEFINED, 65, 1, 1, "AnalogBalance", std::ptr::null_mut()),
    field!(50728, -1, -1, TIFF_RATIONAL, 0, TIFF_SETGET_C16_FLOAT, TIFF_SETGET_UNDEFINED, 65, 1, 1, "AsShotNeutral", std::ptr::null_mut()),
    field!(50729, 2, 2, TIFF_RATIONAL, 0, TIFF_SETGET_C0_FLOAT, TIFF_SETGET_UNDEFINED, 65, 1, 0, "AsShotWhiteXY", std::ptr::null_mut()),
    field!(50730, 1, 1, TIFF_SRATIONAL, 0, TIFF_SETGET_FLOAT, TIFF_SETGET_UNDEFINED, 65, 1, 0, "BaselineExposure", std::ptr::null_mut()),
    field!(50731, 1, 1, TIFF_RATIONAL, 0, TIFF_SETGET_FLOAT, TIFF_SETGET_UNDEFINED, 65, 1, 0, "BaselineNoise", std::ptr::null_mut()),
    field!(50732, 1, 1, TIFF_RATIONAL, 0, TIFF_SETGET_FLOAT, TIFF_SETGET_UNDEFINED, 65, 1, 0, "BaselineSharpness", std::ptr::null_mut()),
    field!(50733, 1, 1, TIFF_LONG, 0, TIFF_SETGET_UINT32, TIFF_SETGET_UNDEFINED, 65, 1, 0, "BayerGreenSplit", std::ptr::null_mut()),
    field!(50734, 1, 1, TIFF_RATIONAL, 0, TIFF_SETGET_FLOAT, TIFF_SETGET_UNDEFINED, 65, 1, 0, "LinearResponseLimit", std::ptr::null_mut()),
    field!(50735, -1, -1, TIFF_ASCII, 0, TIFF_SETGET_ASCII, TIFF_SETGET_UNDEFINED, 65, 1, 0, "CameraSerialNumber", std::ptr::null_mut()),
    field!(50736, 4, 4, TIFF_RATIONAL, 0, TIFF_SETGET_C0_FLOAT, TIFF_SETGET_UNDEFINED, 65, 1, 0, "LensInfo", std::ptr::null_mut()),
    field!(50737, 1, 1, TIFF_RATIONAL, 0, TIFF_SETGET_FLOAT, TIFF_SETGET_UNDEFINED, 65, 1, 0, "ChromaBlurRadius", std::ptr::null_mut()),
    field!(50738, 1, 1, TIFF_RATIONAL, 0, TIFF_SETGET_FLOAT, TIFF_SETGET_UNDEFINED, 65, 1, 0, "AntiAliasStrength", std::ptr::null_mut()),
    field!(50739, 1, 1, TIFF_RATIONAL, 0, TIFF_SETGET_FLOAT, TIFF_SETGET_UNDEFINED, 65, 1, 0, "ShadowScale", std::ptr::null_mut()),
    field!(50740, -1, -1, TIFF_BYTE, 0, TIFF_SETGET_C16_UINT8, TIFF_SETGET_UNDEFINED, 65, 1, 1, "DNGPrivateData", std::ptr::null_mut()),
    field!(50741, 1, 1, TIFF_SHORT, 0, TIFF_SETGET_UINT16, TIFF_SETGET_UNDEFINED, 65, 1, 0, "MakerNoteSafety", std::ptr::null_mut()),
    field!(50778, 1, 1, TIFF_SHORT, 0, TIFF_SETGET_UINT16, TIFF_SETGET_UNDEFINED, 65, 1, 0, "CalibrationIlluminant1", std::ptr::null_mut()),
    field!(50779, 1, 1, TIFF_SHORT, 0, TIFF_SETGET_UINT16, TIFF_SETGET_UNDEFINED, 65, 1, 0, "CalibrationIlluminant2", std::ptr::null_mut()),
    field!(50781, 16, 16, TIFF_BYTE, 0, TIFF_SETGET_C0_UINT8, TIFF_SETGET_UNDEFINED, 65, 1, 0, "RawDataUniqueID", std::ptr::null_mut()),
    field!(50827, -1, -1, TIFF_BYTE, 0, TIFF_SETGET_C16_UINT8, TIFF_SETGET_UNDEFINED, 65, 1, 1, "OriginalRawFileName", std::ptr::null_mut()),
    field!(50828, -1, -1, TIFF_UNDEFINED, 0, TIFF_SETGET_C16_UINT8, TIFF_SETGET_UNDEFINED, 65, 1, 1, "OriginalRawFileData", std::ptr::null_mut()),
    field!(50829, 4, 4, TIFF_LONG, 0, TIFF_SETGET_C0_UINT32, TIFF_SETGET_UNDEFINED, 65, 1, 0, "ActiveArea", std::ptr::null_mut()),
    field!(50830, -1, -1, TIFF_LONG, 0, TIFF_SETGET_C16_UINT32, TIFF_SETGET_UNDEFINED, 65, 1, 1, "MaskedAreas", std::ptr::null_mut()),
    field!(50831, -1, -1, TIFF_UNDEFINED, 0, TIFF_SETGET_C16_UINT8, TIFF_SETGET_UNDEFINED, 65, 1, 1, "AsShotICCProfile", std::ptr::null_mut()),
    field!(50832, -1, -1, TIFF_SRATIONAL, 0, TIFF_SETGET_C16_FLOAT, TIFF_SETGET_UNDEFINED, 65, 1, 1, "AsShotPreProfileMatrix", std::ptr::null_mut()),
    field!(50833, -1, -1, TIFF_UNDEFINED, 0, TIFF_SETGET_C16_UINT8, TIFF_SETGET_UNDEFINED, 65, 1, 1, "CurrentICCProfile", std::ptr::null_mut()),
    field!(50834, -1, -1, TIFF_SRATIONAL, 0, TIFF_SETGET_C16_FLOAT, TIFF_SETGET_UNDEFINED, 65, 1, 1, "CurrentPreProfileMatrix", std::ptr::null_mut()),
    field!(65563, 0, 0, TIFF_SHORT, 0, TIFF_SETGET_UNDEFINED, TIFF_SETGET_UNDEFINED, 0, 1, 0, "PerSample", std::ptr::null_mut()),
    field!(65536, 0, 0, TIFF_NOTYPE, 0, TIFF_SETGET_INT, TIFF_SETGET_UNDEFINED, 69, 1, 0, "FaxMode", std::ptr::null_mut()),
    field!(65557, 0, 0, TIFF_NOTYPE, 0, TIFF_SETGET_INT, TIFF_SETGET_UNDEFINED, 70, 1, 0, "ZipQuality", std::ptr::null_mut()),
    field!(65570, 0, 0, TIFF_NOTYPE, 0, TIFF_SETGET_INT, TIFF_SETGET_UNDEFINED, 71, 1, 0, "DeflateSubCodec", std::ptr::null_mut()),
    field!(346, 1, 1, TIFF_SHORT, 0, TIFF_SETGET_UINT16, TIFF_SETGET_UNDEFINED, 65, 1, 0, "Indexed", std::ptr::null_mut()),
    field!(400, 1, 1, TIFF_IFD8, 0, TIFF_SETGET_IFD8, TIFF_SETGET_UNDEFINED, 65, 1, 0, "GlobalParametersIFD", std::ptr::null_mut()),
    field!(401, 1, 1, TIFF_LONG, 0, TIFF_SETGET_UINT32, TIFF_SETGET_UNDEFINED, 65, 1, 0, "ProfileType", std::ptr::null_mut()),
    field!(402, 1, 1, TIFF_BYTE, 0, TIFF_SETGET_UINT8, TIFF_SETGET_UNDEFINED, 65, 1, 0, "FaxProfile", std::ptr::null_mut()),
    field!(403, 1, 1, TIFF_LONG, 0, TIFF_SETGET_UINT32, TIFF_SETGET_UNDEFINED, 65, 1, 0, "CodingMethods", std::ptr::null_mut()),
    field!(404, 4, 4, TIFF_BYTE, 0, TIFF_SETGET_C0_UINT8, TIFF_SETGET_UNDEFINED, 65, 1, 0, "VersionYear", std::ptr::null_mut()),
    field!(405, 1, 1, TIFF_BYTE, 0, TIFF_SETGET_UINT8, TIFF_SETGET_UNDEFINED, 65, 1, 0, "ModeNumber", std::ptr::null_mut()),
    field!(433, -1, -1, TIFF_SRATIONAL, 0, TIFF_SETGET_C16_FLOAT, TIFF_SETGET_UNDEFINED, 65, 1, 1, "Decode", std::ptr::null_mut()),
    field!(434, -1, -1, TIFF_SHORT, 0, TIFF_SETGET_C16_UINT16, TIFF_SETGET_UNDEFINED, 65, 1, 1, "ImageBaseColor", std::ptr::null_mut()),
    field!(435, 1, 1, TIFF_LONG, 0, TIFF_SETGET_UINT32, TIFF_SETGET_UNDEFINED, 65, 1, 0, "T82Options", std::ptr::null_mut()),
    field!(559, -1, -1, TIFF_LONG, 0, TIFF_SETGET_C16_UINT32, TIFF_SETGET_UNDEFINED, 65, 1, 1, "StripRowCounts", std::ptr::null_mut()),
    field!(34732, 2, 2, TIFF_LONG, 0, TIFF_SETGET_C0_UINT32, TIFF_SETGET_UNDEFINED, 65, 1, 0, "ImageLayer", std::ptr::null_mut()),
];

pub(crate) static TIFF_FIELD_ARRAY_IMAGE: TIFFFieldArray = TIFFFieldArray {
    r#type: TIFFFieldArrayType::tfiatImage,
    allocated_size: 0,
    count: TIFF_FIELDS_IMAGE.len() as u32,
    fields: TIFF_FIELDS_IMAGE.as_ptr() as *mut TIFFField,
};

pub(crate) static TIFF_FIELDS_EXIF: [TIFFField; 81] = [
    field!(33434, 1, 1, TIFF_RATIONAL, 0, TIFF_SETGET_FLOAT, TIFF_SETGET_UNDEFINED, 65, 1, 0, "ExposureTime", std::ptr::null_mut()),
    field!(33437, 1, 1, TIFF_RATIONAL, 0, TIFF_SETGET_FLOAT, TIFF_SETGET_UNDEFINED, 65, 1, 0, "FNumber", std::ptr::null_mut()),
    field!(34850, 1, 1, TIFF_SHORT, 0, TIFF_SETGET_UINT16, TIFF_SETGET_UNDEFINED, 65, 1, 0, "ExposureProgram", std::ptr::null_mut()),
    field!(34852, -1, -1, TIFF_ASCII, 0, TIFF_SETGET_ASCII, TIFF_SETGET_UNDEFINED, 65, 1, 0, "SpectralSensitivity", std::ptr::null_mut()),
    field!(34855, -1, -1, TIFF_SHORT, 0, TIFF_SETGET_C16_UINT16, TIFF_SETGET_UNDEFINED, 65, 1, 1, "ISOSpeedRatings", std::ptr::null_mut()),
    field!(34856, -1, -1, TIFF_UNDEFINED, 0, TIFF_SETGET_C16_UINT8, TIFF_SETGET_UNDEFINED, 65, 1, 1, "OptoelectricConversionFactor", std::ptr::null_mut()),
    field!(34864, 1, 1, TIFF_SHORT, 0, TIFF_SETGET_UINT16, TIFF_SETGET_UNDEFINED, 65, 1, 0, "SensitivityType", std::ptr::null_mut()),
    field!(34865, 1, 1, TIFF_LONG, 0, TIFF_SETGET_UINT32, TIFF_SETGET_UNDEFINED, 65, 1, 0, "StandardOutputSensitivity", std::ptr::null_mut()),
    field!(34866, 1, 1, TIFF_LONG, 0, TIFF_SETGET_UINT32, TIFF_SETGET_UNDEFINED, 65, 1, 0, "RecommendedExposureIndex", std::ptr::null_mut()),
    field!(34867, 1, 1, TIFF_LONG, 0, TIFF_SETGET_UINT32, TIFF_SETGET_UNDEFINED, 65, 1, 0, "ISOSpeed", std::ptr::null_mut()),
    field!(34868, 1, 1, TIFF_LONG, 0, TIFF_SETGET_UINT32, TIFF_SETGET_UNDEFINED, 65, 1, 0, "ISOSpeedLatitudeyyy", std::ptr::null_mut()),
    field!(34869, 1, 1, TIFF_LONG, 0, TIFF_SETGET_UINT32, TIFF_SETGET_UNDEFINED, 65, 1, 0, "ISOSpeedLatitudezzz", std::ptr::null_mut()),
    field!(36864, 4, 4, TIFF_UNDEFINED, 0, TIFF_SETGET_C0_UINT8, TIFF_SETGET_UNDEFINED, 65, 1, 0, "ExifVersion", std::ptr::null_mut()),
    field!(36867, 20, 20, TIFF_ASCII, 0, TIFF_SETGET_ASCII, TIFF_SETGET_UNDEFINED, 65, 1, 0, "DateTimeOriginal", std::ptr::null_mut()),
    field!(36868, 20, 20, TIFF_ASCII, 0, TIFF_SETGET_ASCII, TIFF_SETGET_UNDEFINED, 65, 1, 0, "DateTimeDigitized", std::ptr::null_mut()),
    field!(36880, 7, 7, TIFF_ASCII, 0, TIFF_SETGET_ASCII, TIFF_SETGET_UNDEFINED, 65, 1, 0, "OffsetTime", std::ptr::null_mut()),
    field!(36881, 7, 7, TIFF_ASCII, 0, TIFF_SETGET_ASCII, TIFF_SETGET_UNDEFINED, 65, 1, 0, "OffsetTimeOriginal", std::ptr::null_mut()),
    field!(36882, 7, 7, TIFF_ASCII, 0, TIFF_SETGET_ASCII, TIFF_SETGET_UNDEFINED, 65, 1, 0, "OffsetTimeDigitized", std::ptr::null_mut()),
    field!(37121, 4, 4, TIFF_UNDEFINED, 0, TIFF_SETGET_C0_UINT8, TIFF_SETGET_UNDEFINED, 65, 1, 0, "ComponentsConfiguration", std::ptr::null_mut()),
    field!(37122, 1, 1, TIFF_RATIONAL, 0, TIFF_SETGET_FLOAT, TIFF_SETGET_UNDEFINED, 65, 1, 0, "CompressedBitsPerPixel", std::ptr::null_mut()),
    field!(37377, 1, 1, TIFF_SRATIONAL, 0, TIFF_SETGET_FLOAT, TIFF_SETGET_UNDEFINED, 65, 1, 0, "ShutterSpeedValue", std::ptr::null_mut()),
    field!(37378, 1, 1, TIFF_RATIONAL, 0, TIFF_SETGET_FLOAT, TIFF_SETGET_UNDEFINED, 65, 1, 0, "ApertureValue", std::ptr::null_mut()),
    field!(37379, 1, 1, TIFF_SRATIONAL, 0, TIFF_SETGET_FLOAT, TIFF_SETGET_UNDEFINED, 65, 1, 0, "BrightnessValue", std::ptr::null_mut()),
    field!(37380, 1, 1, TIFF_SRATIONAL, 0, TIFF_SETGET_FLOAT, TIFF_SETGET_UNDEFINED, 65, 1, 0, "ExposureBiasValue", std::ptr::null_mut()),
    field!(37381, 1, 1, TIFF_RATIONAL, 0, TIFF_SETGET_FLOAT, TIFF_SETGET_UNDEFINED, 65, 1, 0, "MaxApertureValue", std::ptr::null_mut()),
    field!(37382, 1, 1, TIFF_RATIONAL, 0, TIFF_SETGET_FLOAT, TIFF_SETGET_UNDEFINED, 65, 1, 0, "SubjectDistance", std::ptr::null_mut()),
    field!(37383, 1, 1, TIFF_SHORT, 0, TIFF_SETGET_UINT16, TIFF_SETGET_UNDEFINED, 65, 1, 0, "MeteringMode", std::ptr::null_mut()),
    field!(37384, 1, 1, TIFF_SHORT, 0, TIFF_SETGET_UINT16, TIFF_SETGET_UNDEFINED, 65, 1, 0, "LightSource", std::ptr::null_mut()),
    field!(37385, 1, 1, TIFF_SHORT, 0, TIFF_SETGET_UINT16, TIFF_SETGET_UNDEFINED, 65, 1, 0, "Flash", std::ptr::null_mut()),
    field!(37386, 1, 1, TIFF_RATIONAL, 0, TIFF_SETGET_FLOAT, TIFF_SETGET_UNDEFINED, 65, 1, 0, "FocalLength", std::ptr::null_mut()),
    field!(37396, -1, -1, TIFF_SHORT, 0, TIFF_SETGET_C16_UINT16, TIFF_SETGET_UNDEFINED, 65, 1, 1, "SubjectArea", std::ptr::null_mut()),
    field!(37500, -1, -1, TIFF_UNDEFINED, 0, TIFF_SETGET_C16_UINT8, TIFF_SETGET_UNDEFINED, 65, 1, 1, "MakerNote", std::ptr::null_mut()),
    field!(37510, -1, -1, TIFF_UNDEFINED, 0, TIFF_SETGET_C16_UINT8, TIFF_SETGET_UNDEFINED, 65, 1, 1, "UserComment", std::ptr::null_mut()),
    field!(37520, -1, -1, TIFF_ASCII, 0, TIFF_SETGET_ASCII, TIFF_SETGET_UNDEFINED, 65, 1, 0, "SubSecTime", std::ptr::null_mut()),
    field!(37521, -1, -1, TIFF_ASCII, 0, TIFF_SETGET_ASCII, TIFF_SETGET_UNDEFINED, 65, 1, 0, "SubSecTimeOriginal", std::ptr::null_mut()),
    field!(37522, -1, -1, TIFF_ASCII, 0, TIFF_SETGET_ASCII, TIFF_SETGET_UNDEFINED, 65, 1, 0, "SubSecTimeDigitized", std::ptr::null_mut()),
    field!(37888, 1, 1, TIFF_SRATIONAL, 0, TIFF_SETGET_FLOAT, TIFF_SETGET_UNDEFINED, 65, 1, 0, "Temperature", std::ptr::null_mut()),
    field!(37889, 1, 1, TIFF_RATIONAL, 0, TIFF_SETGET_FLOAT, TIFF_SETGET_UNDEFINED, 65, 1, 0, "Humidity", std::ptr::null_mut()),
    field!(37890, 1, 1, TIFF_RATIONAL, 0, TIFF_SETGET_FLOAT, TIFF_SETGET_UNDEFINED, 65, 1, 0, "Pressure", std::ptr::null_mut()),
    field!(37891, 1, 1, TIFF_SRATIONAL, 0, TIFF_SETGET_FLOAT, TIFF_SETGET_UNDEFINED, 65, 1, 0, "WaterDepth", std::ptr::null_mut()),
    field!(37892, 1, 1, TIFF_RATIONAL, 0, TIFF_SETGET_FLOAT, TIFF_SETGET_UNDEFINED, 65, 1, 0, "Acceleration", std::ptr::null_mut()),
    field!(37893, 1, 1, TIFF_SRATIONAL, 0, TIFF_SETGET_FLOAT, TIFF_SETGET_UNDEFINED, 65, 1, 0, "CameraElevationAngle", std::ptr::null_mut()),
    field!(40960, 4, 4, TIFF_UNDEFINED, 0, TIFF_SETGET_C0_UINT8, TIFF_SETGET_UNDEFINED, 65, 1, 0, "FlashpixVersion", std::ptr::null_mut()),
    field!(40961, 1, 1, TIFF_SHORT, 0, TIFF_SETGET_UINT16, TIFF_SETGET_UNDEFINED, 65, 1, 0, "ColorSpace", std::ptr::null_mut()),
    field!(40962, 1, 1, TIFF_LONG, 0, TIFF_SETGET_UINT32, TIFF_SETGET_UNDEFINED, 65, 1, 0, "PixelXDimension", std::ptr::null_mut()),
    field!(40963, 1, 1, TIFF_LONG, 0, TIFF_SETGET_UINT32, TIFF_SETGET_UNDEFINED, 65, 1, 0, "PixelYDimension", std::ptr::null_mut()),
    field!(40964, 13, 13, TIFF_ASCII, 0, TIFF_SETGET_ASCII, TIFF_SETGET_UNDEFINED, 65, 1, 0, "RelatedSoundFile", std::ptr::null_mut()),
    field!(41483, 1, 1, TIFF_RATIONAL, 0, TIFF_SETGET_FLOAT, TIFF_SETGET_UNDEFINED, 65, 1, 0, "FlashEnergy", std::ptr::null_mut()),
    field!(41484, -1, -1, TIFF_UNDEFINED, 0, TIFF_SETGET_C16_UINT8, TIFF_SETGET_UNDEFINED, 65, 1, 1, "SpatialFrequencyResponse", std::ptr::null_mut()),
    field!(41486, 1, 1, TIFF_RATIONAL, 0, TIFF_SETGET_FLOAT, TIFF_SETGET_UNDEFINED, 65, 1, 0, "FocalPlaneXResolution", std::ptr::null_mut()),
    field!(41487, 1, 1, TIFF_RATIONAL, 0, TIFF_SETGET_FLOAT, TIFF_SETGET_UNDEFINED, 65, 1, 0, "FocalPlaneYResolution", std::ptr::null_mut()),
    field!(41488, 1, 1, TIFF_SHORT, 0, TIFF_SETGET_UINT16, TIFF_SETGET_UNDEFINED, 65, 1, 0, "FocalPlaneResolutionUnit", std::ptr::null_mut()),
    field!(41492, 2, 2, TIFF_SHORT, 0, TIFF_SETGET_C0_UINT16, TIFF_SETGET_UNDEFINED, 65, 1, 0, "SubjectLocation", std::ptr::null_mut()),
    field!(41493, 1, 1, TIFF_RATIONAL, 0, TIFF_SETGET_FLOAT, TIFF_SETGET_UNDEFINED, 65, 1, 0, "ExposureIndex", std::ptr::null_mut()),
    field!(41495, 1, 1, TIFF_SHORT, 0, TIFF_SETGET_UINT16, TIFF_SETGET_UNDEFINED, 65, 1, 0, "SensingMethod", std::ptr::null_mut()),
    field!(41728, 1, 1, TIFF_UNDEFINED, 0, TIFF_SETGET_UINT8, TIFF_SETGET_UNDEFINED, 65, 1, 0, "FileSource", std::ptr::null_mut()),
    field!(41729, 1, 1, TIFF_UNDEFINED, 0, TIFF_SETGET_UINT8, TIFF_SETGET_UNDEFINED, 65, 1, 0, "SceneType", std::ptr::null_mut()),
    field!(41730, -1, -1, TIFF_UNDEFINED, 0, TIFF_SETGET_C16_UINT8, TIFF_SETGET_UNDEFINED, 65, 1, 1, "CFAPattern", std::ptr::null_mut()),
    field!(41985, 1, 1, TIFF_SHORT, 0, TIFF_SETGET_UINT16, TIFF_SETGET_UNDEFINED, 65, 1, 0, "CustomRendered", std::ptr::null_mut()),
    field!(41986, 1, 1, TIFF_SHORT, 0, TIFF_SETGET_UINT16, TIFF_SETGET_UNDEFINED, 65, 1, 0, "ExposureMode", std::ptr::null_mut()),
    field!(41987, 1, 1, TIFF_SHORT, 0, TIFF_SETGET_UINT16, TIFF_SETGET_UNDEFINED, 65, 1, 0, "WhiteBalance", std::ptr::null_mut()),
    field!(41988, 1, 1, TIFF_RATIONAL, 0, TIFF_SETGET_FLOAT, TIFF_SETGET_UNDEFINED, 65, 1, 0, "DigitalZoomRatio", std::ptr::null_mut()),
    field!(41989, 1, 1, TIFF_SHORT, 0, TIFF_SETGET_UINT16, TIFF_SETGET_UNDEFINED, 65, 1, 0, "FocalLengthIn35mmFilm", std::ptr::null_mut()),
    field!(41990, 1, 1, TIFF_SHORT, 0, TIFF_SETGET_UINT16, TIFF_SETGET_UNDEFINED, 65, 1, 0, "SceneCaptureType", std::ptr::null_mut()),
    field!(41991, 1, 1, TIFF_RATIONAL, 0, TIFF_SETGET_FLOAT, TIFF_SETGET_UNDEFINED, 65, 1, 0, "GainControl", std::ptr::null_mut()),
    field!(41992, 1, 1, TIFF_SHORT, 0, TIFF_SETGET_UINT16, TIFF_SETGET_UNDEFINED, 65, 1, 0, "Contrast", std::ptr::null_mut()),
    field!(41993, 1, 1, TIFF_SHORT, 0, TIFF_SETGET_UINT16, TIFF_SETGET_UNDEFINED, 65, 1, 0, "Saturation", std::ptr::null_mut()),
    field!(41994, 1, 1, TIFF_SHORT, 0, TIFF_SETGET_UINT16, TIFF_SETGET_UNDEFINED, 65, 1, 0, "Sharpness", std::ptr::null_mut()),
    field!(41995, -1, -1, TIFF_UNDEFINED, 0, TIFF_SETGET_C16_UINT8, TIFF_SETGET_UNDEFINED, 65, 1, 1, "DeviceSettingDescription", std::ptr::null_mut()),
    field!(41996, 1, 1, TIFF_SHORT, 0, TIFF_SETGET_UINT16, TIFF_SETGET_UNDEFINED, 65, 1, 0, "SubjectDistanceRange", std::ptr::null_mut()),
    field!(42016, 33, 33, TIFF_ASCII, 0, TIFF_SETGET_ASCII, TIFF_SETGET_UNDEFINED, 65, 1, 0, "ImageUniqueID", std::ptr::null_mut()),
    field!(42032, -1, -1, TIFF_ASCII, 0, TIFF_SETGET_ASCII, TIFF_SETGET_UNDEFINED, 65, 1, 0, "CameraOwnerName", std::ptr::null_mut()),
    field!(42033, -1, -1, TIFF_ASCII, 0, TIFF_SETGET_ASCII, TIFF_SETGET_UNDEFINED, 65, 1, 0, "BodySerialNumber", std::ptr::null_mut()),
    field!(42034, 4, 4, TIFF_RATIONAL, 0, TIFF_SETGET_C0_FLOAT, TIFF_SETGET_UNDEFINED, 65, 1, 0, "LensSpecification", std::ptr::null_mut()),
    field!(42035, -1, -1, TIFF_ASCII, 0, TIFF_SETGET_ASCII, TIFF_SETGET_UNDEFINED, 65, 1, 0, "LensMake", std::ptr::null_mut()),
    field!(42036, -1, -1, TIFF_ASCII, 0, TIFF_SETGET_ASCII, TIFF_SETGET_UNDEFINED, 65, 1, 0, "LensModel", std::ptr::null_mut()),
    field!(42037, -1, -1, TIFF_ASCII, 0, TIFF_SETGET_ASCII, TIFF_SETGET_UNDEFINED, 65, 1, 0, "LensSerialNumber", std::ptr::null_mut()),
    field!(42240, 1, 1, TIFF_RATIONAL, 0, TIFF_SETGET_FLOAT, TIFF_SETGET_UNDEFINED, 65, 1, 0, "Gamma", std::ptr::null_mut()),
    field!(42080, 1, 1, TIFF_SHORT, 0, TIFF_SETGET_UINT16, TIFF_SETGET_UNDEFINED, 65, 1, 0, "CompositeImage", std::ptr::null_mut()),
    field!(42081, 2, 2, TIFF_SHORT, 0, TIFF_SETGET_C0_UINT16, TIFF_SETGET_UNDEFINED, 65, 1, 0, "SourceImageNumberOfCompositeImage", std::ptr::null_mut()),
    field!(42082, -1, -1, TIFF_UNDEFINED, 0, TIFF_SETGET_C16_UINT8, TIFF_SETGET_UNDEFINED, 65, 1, 1, "SourceExposureTimesOfCompositeImage", std::ptr::null_mut()),
];

pub(crate) static TIFF_FIELD_ARRAY_EXIF: TIFFFieldArray = TIFFFieldArray {
    r#type: TIFFFieldArrayType::tfiatExif,
    allocated_size: 0,
    count: TIFF_FIELDS_EXIF.len() as u32,
    fields: TIFF_FIELDS_EXIF.as_ptr() as *mut TIFFField,
};

pub(crate) static TIFF_FIELDS_GPS: [TIFFField; 32] = [
    field!(0, 4, 4, TIFF_BYTE, 0, TIFF_SETGET_C0_UINT8, TIFF_SETGET_UINT8, 65, 1, 0, "VersionID", std::ptr::null_mut()),
    field!(1, 2, 2, TIFF_ASCII, 0, TIFF_SETGET_ASCII, TIFF_SETGET_UNDEFINED, 65, 1, 0, "LatitudeRef", std::ptr::null_mut()),
    field!(2, 3, 3, TIFF_RATIONAL, 0, TIFF_SETGET_C0_DOUBLE, TIFF_SETGET_UNDEFINED, 65, 1, 0, "Latitude", std::ptr::null_mut()),
    field!(3, 2, 2, TIFF_ASCII, 0, TIFF_SETGET_ASCII, TIFF_SETGET_UNDEFINED, 65, 1, 0, "LongitudeRef", std::ptr::null_mut()),
    field!(4, 3, 3, TIFF_RATIONAL, 0, TIFF_SETGET_C0_DOUBLE, TIFF_SETGET_UNDEFINED, 65, 1, 0, "Longitude", std::ptr::null_mut()),
    field!(5, 1, 1, TIFF_BYTE, 0, TIFF_SETGET_UINT8, TIFF_SETGET_UNDEFINED, 65, 1, 0, "AltitudeRef", std::ptr::null_mut()),
    field!(6, 1, 1, TIFF_RATIONAL, 0, TIFF_SETGET_DOUBLE, TIFF_SETGET_UNDEFINED, 65, 1, 0, "Altitude", std::ptr::null_mut()),
    field!(7, 3, 3, TIFF_RATIONAL, 0, TIFF_SETGET_C0_DOUBLE, TIFF_SETGET_UNDEFINED, 65, 1, 0, "TimeStamp", std::ptr::null_mut()),
    field!(8, -1, -1, TIFF_ASCII, 0, TIFF_SETGET_ASCII, TIFF_SETGET_UNDEFINED, 65, 1, 0, "Satellites", std::ptr::null_mut()),
    field!(9, 2, 2, TIFF_ASCII, 0, TIFF_SETGET_ASCII, TIFF_SETGET_UNDEFINED, 65, 1, 0, "Status", std::ptr::null_mut()),
    field!(10, 2, 2, TIFF_ASCII, 0, TIFF_SETGET_ASCII, TIFF_SETGET_UNDEFINED, 65, 1, 0, "MeasureMode", std::ptr::null_mut()),
    field!(11, 1, 1, TIFF_RATIONAL, 0, TIFF_SETGET_DOUBLE, TIFF_SETGET_UNDEFINED, 65, 1, 0, "DOP", std::ptr::null_mut()),
    field!(12, 2, 2, TIFF_ASCII, 0, TIFF_SETGET_ASCII, TIFF_SETGET_UNDEFINED, 65, 1, 0, "SpeedRef", std::ptr::null_mut()),
    field!(13, 1, 1, TIFF_RATIONAL, 0, TIFF_SETGET_DOUBLE, TIFF_SETGET_UNDEFINED, 65, 1, 0, "Speed", std::ptr::null_mut()),
    field!(14, 2, 2, TIFF_ASCII, 0, TIFF_SETGET_ASCII, TIFF_SETGET_UNDEFINED, 65, 1, 0, "TrackRef", std::ptr::null_mut()),
    field!(15, 1, 1, TIFF_RATIONAL, 0, TIFF_SETGET_DOUBLE, TIFF_SETGET_UNDEFINED, 65, 1, 0, "Track", std::ptr::null_mut()),
    field!(16, 2, 2, TIFF_ASCII, 0, TIFF_SETGET_ASCII, TIFF_SETGET_UNDEFINED, 65, 1, 0, "ImgDirectionRef", std::ptr::null_mut()),
    field!(17, 1, 1, TIFF_RATIONAL, 0, TIFF_SETGET_DOUBLE, TIFF_SETGET_UNDEFINED, 65, 1, 0, "ImgDirection", std::ptr::null_mut()),
    field!(18, -1, -1, TIFF_ASCII, 0, TIFF_SETGET_ASCII, TIFF_SETGET_UNDEFINED, 65, 1, 0, "MapDatum", std::ptr::null_mut()),
    field!(19, 2, 2, TIFF_ASCII, 0, TIFF_SETGET_ASCII, TIFF_SETGET_UNDEFINED, 65, 1, 0, "DestLatitudeRef", std::ptr::null_mut()),
    field!(20, 3, 3, TIFF_RATIONAL, 0, TIFF_SETGET_C0_DOUBLE, TIFF_SETGET_UNDEFINED, 65, 1, 0, "DestLatitude", std::ptr::null_mut()),
    field!(21, 2, 2, TIFF_ASCII, 0, TIFF_SETGET_ASCII, TIFF_SETGET_UNDEFINED, 65, 1, 0, "DestLongitudeRef", std::ptr::null_mut()),
    field!(22, 3, 3, TIFF_RATIONAL, 0, TIFF_SETGET_C0_DOUBLE, TIFF_SETGET_UNDEFINED, 65, 1, 0, "DestLongitude", std::ptr::null_mut()),
    field!(23, 2, 2, TIFF_ASCII, 0, TIFF_SETGET_ASCII, TIFF_SETGET_UNDEFINED, 65, 1, 0, "DestBearingRef", std::ptr::null_mut()),
    field!(24, 1, 1, TIFF_RATIONAL, 0, TIFF_SETGET_DOUBLE, TIFF_SETGET_UNDEFINED, 65, 1, 0, "DestBearing", std::ptr::null_mut()),
    field!(25, 2, 2, TIFF_ASCII, 0, TIFF_SETGET_ASCII, TIFF_SETGET_UNDEFINED, 65, 1, 0, "DestDistanceRef", std::ptr::null_mut()),
    field!(26, 1, 1, TIFF_RATIONAL, 0, TIFF_SETGET_DOUBLE, TIFF_SETGET_UNDEFINED, 65, 1, 0, "DestDistance", std::ptr::null_mut()),
    field!(27, -1, -1, TIFF_UNDEFINED, 0, TIFF_SETGET_C16_UINT8, TIFF_SETGET_UNDEFINED, 65, 1, 1, "ProcessingMethod", std::ptr::null_mut()),
    field!(28, -1, -1, TIFF_UNDEFINED, 0, TIFF_SETGET_C16_UINT8, TIFF_SETGET_UNDEFINED, 65, 1, 1, "AreaInformation", std::ptr::null_mut()),
    field!(29, 11, 11, TIFF_ASCII, 0, TIFF_SETGET_ASCII, TIFF_SETGET_UNDEFINED, 65, 1, 0, "DateStamp", std::ptr::null_mut()),
    field!(30, 1, 1, TIFF_SHORT, 0, TIFF_SETGET_UINT16, TIFF_SETGET_UNDEFINED, 65, 1, 0, "Differential", std::ptr::null_mut()),
    field!(31, 1, 1, TIFF_RATIONAL, 0, TIFF_SETGET_DOUBLE, TIFF_SETGET_UNDEFINED, 65, 1, 0, "HorizontalPositioningError", std::ptr::null_mut()),
];

pub(crate) static TIFF_FIELD_ARRAY_GPS: TIFFFieldArray = TIFFFieldArray {
    r#type: TIFFFieldArrayType::tfiatGps,
    allocated_size: 0,
    count: TIFF_FIELDS_GPS.len() as u32,
    fields: TIFF_FIELDS_GPS.as_ptr() as *mut TIFFField,
};
